graph TD
  STATE_overview_landscape_0fc42b6ad76a["overview_landscape\n(idle)"]
  STATE_overview_landscape_d5cb451a21ea["overview_landscape\n(idle)"]
  STATE_headquarters_58ebaae766b9["headquarters\n(idle)"]
  STATE_overview_landscape_05249c6e9f5f["overview_landscape\n(finished)"]
  STATE_encyclopedia_29639c31d31a["encyclopedia\n(idle)"]
  STATE_overview_landscape_12e8f55b95e7["overview_landscape\n(idle)"]
  STATE_warehouse_1cc464b6e905["warehouse\n(idle)"]
  STATE_overview_landscape_3cf578da11e8["overview_landscape\n(idle)"]
  STATE_messages_9d477833186c["messages\n(idle)"]
  STATE_market_70b53113c8b7["market\n(idle)"]
  START -->|"✔ navigate:http:/"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"✔ 开始游戏"| STATE_overview_landscape_d5cb451a21ea
  STATE_overview_landscape_0fc42b6ad76a -->|"? 登录"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 登录"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? $1.00"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? Switch language"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? Pause"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? Trailer"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? Trailer"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 开始游戏"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 登录"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 登录"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 经济模拟模型"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 4.7/518,420 条评价"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 4.8/59,210 条评价"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 4.6/54,380 条评价"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 4.5/52,342 条评价"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 显示更多"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 显示更多"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 显示更多"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 显示更多"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 显示更多"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? Solaris Energy "| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? AeroTech System"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? Titan Industrie"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? Solaris Energy "| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? AeroTech System"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? Titan Industrie"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 最新一期《Sim Compan"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 新人指南"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 商业大亨 的证书浏览器"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 经济模拟模型"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 常见问题"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 百科"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 变更日志"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 显示更多"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 开始游戏"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 经济模拟模型"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 开始游戏"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 开始游戏"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 新人指南"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 开始游戏"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 常见问题"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 开始游戏"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 经济模拟模型"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 开始游戏"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 常见问题"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 游玩《Sim Energy E"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 为了学校"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 关于"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? Bug报告"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 常见问题"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 隐私政策"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? Cookie政策"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 使用条款"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? Cookie政策"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 隐私政策"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 全部接受"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 仅限必要"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_0fc42b6ad76a -->|"? 自订Cookie"| STATE_overview_landscape_0fc42b6ad76a
  STATE_overview_landscape_d5cb451a21ea -->|"✔ $100,000"| STATE_headquarters_58ebaae766b9
  STATE_overview_landscape_d5cb451a21ea -->|"✔ 250"| STATE_overview_landscape_05249c6e9f5f
  STATE_overview_landscape_d5cb451a21ea -->|"✔ Lv. 0 (0%)"| STATE_encyclopedia_29639c31d31a
  STATE_overview_landscape_d5cb451a21ea -->|"✔ Map"| STATE_overview_landscape_12e8f55b95e7
  STATE_overview_landscape_d5cb451a21ea -->|"✔ Warehouse"| STATE_warehouse_1cc464b6e905
  STATE_overview_landscape_d5cb451a21ea -->|"✔ Search"| STATE_overview_landscape_3cf578da11e8
  STATE_overview_landscape_d5cb451a21ea -->|"✔ Chat"| STATE_messages_9d477833186c
  STATE_overview_landscape_d5cb451a21ea -->|"✔ Exchange"| STATE_market_70b53113c8b7
  STATE_headquarters_58ebaae766b9 -->|"✔ 0"| STATE_overview_landscape_3cf578da11e8
