name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
      - gh-pages
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare Artifact
        run: |
          mkdir -p _site
          if [ -f "historical/2019/showcase/index.html" ]; then
            cp historical/2019/showcase/index.html _site/index.html
          elif [ -f "docs/index.html" ]; then
            cp docs/index.html _site/index.html
          else
            cp index.html _site/index.html
          fi
          touch _site/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
